# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.28.2/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.28.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/lorenzo/Executables/Source/Note

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/lorenzo/Executables/Source/Note

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.28.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/lorenzo/Executables/Source/Note/CMakeFiles /Users/lorenzo/Executables/Source/Note//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/lorenzo/Executables/Source/Note/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MyNoteBook

# Build rule for target.
MyNoteBook: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MyNoteBook
.PHONY : MyNoteBook

# fast build rule for target.
MyNoteBook/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyNoteBook.dir/build.make CMakeFiles/MyNoteBook.dir/build
.PHONY : MyNoteBook/fast

#=============================================================================
# Target rules for targets named shownotebook

# Build rule for target.
shownotebook: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 shownotebook
.PHONY : shownotebook

# fast build rule for target.
shownotebook/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shownotebook.dir/build.make CMakeFiles/shownotebook.dir/build
.PHONY : shownotebook/fast

#=============================================================================
# Target rules for targets named createnotebook

# Build rule for target.
createnotebook: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 createnotebook
.PHONY : createnotebook

# fast build rule for target.
createnotebook/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/createnotebook.dir/build.make CMakeFiles/createnotebook.dir/build
.PHONY : createnotebook/fast

#=============================================================================
# Target rules for targets named addnote

# Build rule for target.
addnote: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 addnote
.PHONY : addnote

# fast build rule for target.
addnote/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/addnote.dir/build.make CMakeFiles/addnote.dir/build
.PHONY : addnote/fast

#=============================================================================
# Target rules for targets named cleannotebook

# Build rule for target.
cleannotebook: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cleannotebook
.PHONY : cleannotebook

# fast build rule for target.
cleannotebook/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cleannotebook.dir/build.make CMakeFiles/cleannotebook.dir/build
.PHONY : cleannotebook/fast

app/MyNotebook.o: app/MyNotebook.cxx.o
.PHONY : app/MyNotebook.o

# target to build an object file
app/MyNotebook.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyNoteBook.dir/build.make CMakeFiles/MyNoteBook.dir/app/MyNotebook.cxx.o
.PHONY : app/MyNotebook.cxx.o

app/MyNotebook.i: app/MyNotebook.cxx.i
.PHONY : app/MyNotebook.i

# target to preprocess a source file
app/MyNotebook.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyNoteBook.dir/build.make CMakeFiles/MyNoteBook.dir/app/MyNotebook.cxx.i
.PHONY : app/MyNotebook.cxx.i

app/MyNotebook.s: app/MyNotebook.cxx.s
.PHONY : app/MyNotebook.s

# target to generate assembly for a file
app/MyNotebook.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyNoteBook.dir/build.make CMakeFiles/MyNoteBook.dir/app/MyNotebook.cxx.s
.PHONY : app/MyNotebook.cxx.s

app/addNote.o: app/addNote.cxx.o
.PHONY : app/addNote.o

# target to build an object file
app/addNote.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/addnote.dir/build.make CMakeFiles/addnote.dir/app/addNote.cxx.o
.PHONY : app/addNote.cxx.o

app/addNote.i: app/addNote.cxx.i
.PHONY : app/addNote.i

# target to preprocess a source file
app/addNote.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/addnote.dir/build.make CMakeFiles/addnote.dir/app/addNote.cxx.i
.PHONY : app/addNote.cxx.i

app/addNote.s: app/addNote.cxx.s
.PHONY : app/addNote.s

# target to generate assembly for a file
app/addNote.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/addnote.dir/build.make CMakeFiles/addnote.dir/app/addNote.cxx.s
.PHONY : app/addNote.cxx.s

app/cleanNotebook.o: app/cleanNotebook.cxx.o
.PHONY : app/cleanNotebook.o

# target to build an object file
app/cleanNotebook.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cleannotebook.dir/build.make CMakeFiles/cleannotebook.dir/app/cleanNotebook.cxx.o
.PHONY : app/cleanNotebook.cxx.o

app/cleanNotebook.i: app/cleanNotebook.cxx.i
.PHONY : app/cleanNotebook.i

# target to preprocess a source file
app/cleanNotebook.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cleannotebook.dir/build.make CMakeFiles/cleannotebook.dir/app/cleanNotebook.cxx.i
.PHONY : app/cleanNotebook.cxx.i

app/cleanNotebook.s: app/cleanNotebook.cxx.s
.PHONY : app/cleanNotebook.s

# target to generate assembly for a file
app/cleanNotebook.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cleannotebook.dir/build.make CMakeFiles/cleannotebook.dir/app/cleanNotebook.cxx.s
.PHONY : app/cleanNotebook.cxx.s

app/createNotebook.o: app/createNotebook.cxx.o
.PHONY : app/createNotebook.o

# target to build an object file
app/createNotebook.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/createnotebook.dir/build.make CMakeFiles/createnotebook.dir/app/createNotebook.cxx.o
.PHONY : app/createNotebook.cxx.o

app/createNotebook.i: app/createNotebook.cxx.i
.PHONY : app/createNotebook.i

# target to preprocess a source file
app/createNotebook.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/createnotebook.dir/build.make CMakeFiles/createnotebook.dir/app/createNotebook.cxx.i
.PHONY : app/createNotebook.cxx.i

app/createNotebook.s: app/createNotebook.cxx.s
.PHONY : app/createNotebook.s

# target to generate assembly for a file
app/createNotebook.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/createnotebook.dir/build.make CMakeFiles/createnotebook.dir/app/createNotebook.cxx.s
.PHONY : app/createNotebook.cxx.s

app/showNotebook.o: app/showNotebook.cxx.o
.PHONY : app/showNotebook.o

# target to build an object file
app/showNotebook.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shownotebook.dir/build.make CMakeFiles/shownotebook.dir/app/showNotebook.cxx.o
.PHONY : app/showNotebook.cxx.o

app/showNotebook.i: app/showNotebook.cxx.i
.PHONY : app/showNotebook.i

# target to preprocess a source file
app/showNotebook.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shownotebook.dir/build.make CMakeFiles/shownotebook.dir/app/showNotebook.cxx.i
.PHONY : app/showNotebook.cxx.i

app/showNotebook.s: app/showNotebook.cxx.s
.PHONY : app/showNotebook.s

# target to generate assembly for a file
app/showNotebook.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shownotebook.dir/build.make CMakeFiles/shownotebook.dir/app/showNotebook.cxx.s
.PHONY : app/showNotebook.cxx.s

src/Note.o: src/Note.cxx.o
.PHONY : src/Note.o

# target to build an object file
src/Note.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyNoteBook.dir/build.make CMakeFiles/MyNoteBook.dir/src/Note.cxx.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shownotebook.dir/build.make CMakeFiles/shownotebook.dir/src/Note.cxx.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/createnotebook.dir/build.make CMakeFiles/createnotebook.dir/src/Note.cxx.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/addnote.dir/build.make CMakeFiles/addnote.dir/src/Note.cxx.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cleannotebook.dir/build.make CMakeFiles/cleannotebook.dir/src/Note.cxx.o
.PHONY : src/Note.cxx.o

src/Note.i: src/Note.cxx.i
.PHONY : src/Note.i

# target to preprocess a source file
src/Note.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyNoteBook.dir/build.make CMakeFiles/MyNoteBook.dir/src/Note.cxx.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shownotebook.dir/build.make CMakeFiles/shownotebook.dir/src/Note.cxx.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/createnotebook.dir/build.make CMakeFiles/createnotebook.dir/src/Note.cxx.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/addnote.dir/build.make CMakeFiles/addnote.dir/src/Note.cxx.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cleannotebook.dir/build.make CMakeFiles/cleannotebook.dir/src/Note.cxx.i
.PHONY : src/Note.cxx.i

src/Note.s: src/Note.cxx.s
.PHONY : src/Note.s

# target to generate assembly for a file
src/Note.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyNoteBook.dir/build.make CMakeFiles/MyNoteBook.dir/src/Note.cxx.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shownotebook.dir/build.make CMakeFiles/shownotebook.dir/src/Note.cxx.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/createnotebook.dir/build.make CMakeFiles/createnotebook.dir/src/Note.cxx.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/addnote.dir/build.make CMakeFiles/addnote.dir/src/Note.cxx.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cleannotebook.dir/build.make CMakeFiles/cleannotebook.dir/src/Note.cxx.s
.PHONY : src/Note.cxx.s

src/Notebook.o: src/Notebook.cxx.o
.PHONY : src/Notebook.o

# target to build an object file
src/Notebook.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyNoteBook.dir/build.make CMakeFiles/MyNoteBook.dir/src/Notebook.cxx.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shownotebook.dir/build.make CMakeFiles/shownotebook.dir/src/Notebook.cxx.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/createnotebook.dir/build.make CMakeFiles/createnotebook.dir/src/Notebook.cxx.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/addnote.dir/build.make CMakeFiles/addnote.dir/src/Notebook.cxx.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cleannotebook.dir/build.make CMakeFiles/cleannotebook.dir/src/Notebook.cxx.o
.PHONY : src/Notebook.cxx.o

src/Notebook.i: src/Notebook.cxx.i
.PHONY : src/Notebook.i

# target to preprocess a source file
src/Notebook.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyNoteBook.dir/build.make CMakeFiles/MyNoteBook.dir/src/Notebook.cxx.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shownotebook.dir/build.make CMakeFiles/shownotebook.dir/src/Notebook.cxx.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/createnotebook.dir/build.make CMakeFiles/createnotebook.dir/src/Notebook.cxx.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/addnote.dir/build.make CMakeFiles/addnote.dir/src/Notebook.cxx.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cleannotebook.dir/build.make CMakeFiles/cleannotebook.dir/src/Notebook.cxx.i
.PHONY : src/Notebook.cxx.i

src/Notebook.s: src/Notebook.cxx.s
.PHONY : src/Notebook.s

# target to generate assembly for a file
src/Notebook.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyNoteBook.dir/build.make CMakeFiles/MyNoteBook.dir/src/Notebook.cxx.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shownotebook.dir/build.make CMakeFiles/shownotebook.dir/src/Notebook.cxx.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/createnotebook.dir/build.make CMakeFiles/createnotebook.dir/src/Notebook.cxx.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/addnote.dir/build.make CMakeFiles/addnote.dir/src/Notebook.cxx.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cleannotebook.dir/build.make CMakeFiles/cleannotebook.dir/src/Notebook.cxx.s
.PHONY : src/Notebook.cxx.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... MyNoteBook"
	@echo "... addnote"
	@echo "... cleannotebook"
	@echo "... createnotebook"
	@echo "... shownotebook"
	@echo "... app/MyNotebook.o"
	@echo "... app/MyNotebook.i"
	@echo "... app/MyNotebook.s"
	@echo "... app/addNote.o"
	@echo "... app/addNote.i"
	@echo "... app/addNote.s"
	@echo "... app/cleanNotebook.o"
	@echo "... app/cleanNotebook.i"
	@echo "... app/cleanNotebook.s"
	@echo "... app/createNotebook.o"
	@echo "... app/createNotebook.i"
	@echo "... app/createNotebook.s"
	@echo "... app/showNotebook.o"
	@echo "... app/showNotebook.i"
	@echo "... app/showNotebook.s"
	@echo "... src/Note.o"
	@echo "... src/Note.i"
	@echo "... src/Note.s"
	@echo "... src/Notebook.o"
	@echo "... src/Notebook.i"
	@echo "... src/Notebook.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

